{{- if .Values.css.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ask-nginx-web-app.fullname" . }}-conf
  labels:
    {{- include "ask-nginx-web-app.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <center>
    <body style="background-color:{{ .Values.css.background }};">
   <h1> {{ .Values.css.heading }}</h1>
    <div id="app"></div>
    <script src="/app.js"></script>
    </center>
    </body>
    </html>
  {{- end }}
