apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ask-nginx-web-app.fullname" . }}
  labels:
    {{- include "ask-nginx-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_DB_USERNAME: {{ .Values.envSecretsVars.SECRET_DB_USERNAME | b64enc | quote }}
  SECRET_DB_PASSWORD: {{ .Values.envSecretsVars.SECRET_DB_PASSWORD | b64enc | quote }}