apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ask-nginx-web-app.fullname" . }}
  labels:
    {{- include "ask-nginx-web-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}